### ISSUE TITLE
access control et sécurité

### ISSUE THREAD

**Issue by hgouraud** [a2line/geneweb_bootstrap#22]
Le contrôle d’accès à une base, et la protection des données personnelles qu’elle contient est un des rôles important de GeneWeb.
Plusieurs mécanismes sont disponibles :
- restriction globale d’accès au serveur gwd (-auth passwd_file au lancement de gwd)
- restriction globale d’accès à une base (auth_file=passwd_file dans basename.gwf)
- restriction des données visibles par les visiteurs/amis/magiciens/manitou

```
    friend_passwd=, friend_passwd_file=, wizard_passwd=, …
    private_years=300
    use_restrict=yes
    hide_private_names=yes
    public_if_title=no
    public_if_no_date==no
    no_image_for_visitor=yes
    no_note_for_visitor=yes
```

Malheureusement, les deux premiers mécanismes ne sont pas disponibles en mode CGI, et il est nécessaire de se reporter sur le dernier.
Il apparait par ailleurs qu’un visiteur peut malgré tout avoir accès à certaines informations, en manipulant directement les URL d’accès à la base :
- m=NOTES affiche le texte de la note de présentation de la base (acceptable)
- m=MISC_NOTES n’affiche plus les “pages liées” appelées depuis les notes associées aux individus, mais continue à afficher une “page liée” associée à une autre page liée! Probablement à noter comme un **bug**!!
- m=IMH; affiche l’image référencée (malgré le no_images_for_visitors=yes qui n’impacte que les portraits)
- m=SRC; affiche le texte associé (idem)

Proposition :
ajouter dans basename.gwf les variables suivantes :
- visitor_access=yes/no               # défaut yes. Permet de traiter le cas visiteur de façon explicite. Aujourd’hui, seul “yes” est disponible
- no_pictures_for_visitor=yes/no # default no. Idem no_images_for_visitors, mais pour IM(H)
- no_src_for_visitor=yes/no         # default no. Idem no_images_for_visitors, mais pour SRC

Par ailleurs, l’accès à une page liée référencée à partir d’une autre page devrait être traité correctement.

**Comment by hgouraud** [comment]
En mode CGI, les usagers peuvent être authentifiés soit par GeneWeb (visiteurs/amis/magiciens) soit par le serveur web (Apache, .htaccess).
Si l'authentification par le serveur web est utilisée, il est nécessaire aujourd'hui de s'authentifier une seconde fois pour avoir l'accès ami.
visitors_are_friends=yes éviterait cette seconde authentification.

**Comment by a2line** [comment]
Je ne comprends pas ta dernière requête : si tu ne veux pas de mot de passe ami, il suffit de ne pas en mettre, non ?

**Comment by hgouraud** [comment]
Exact, mon erreur! Si il n'y a pas de mot de passe ami, tout le monde est au moins "ami"!!
